
// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class Testresourcenotfoundexception()Test
{


    // Verifies that a GET request to a nonexistent endpoint returns a 404 status
    @Test
    public void test_get_request_to_nonexistent_endpoint_returns_404() throws Exception {
        GlobalExceptionHandlerTest globalExceptionHandlerTest = new GlobalExceptionHandlerTest();
        globalExceptionHandlerTest.testResourceNotFoundException();
    }

    // Tests the response when the endpoint is almost correct but slightly
    // misspelled
    @Test
    public void test_response_for_slightly_misspelled_endpoint() throws Exception {
        mockMvc.perform(get("/nonexistant-endpoint"))
                .andExpect(status().isNotFound())
                .andExpect(content().string("Resource not found"));
    }
}